DEFAULT_CAPTCHA_SIZE = 320
DOT_RADIUS_FLOAT = 10 / DEFAULT_CAPTCHA_SIZE * 1.5
DOT_RADIUS_FLOAT_MOBILE = DOT_RADIUS_FLOAT * 1.5
MODEL_INPUT_SHAPE = (1, 100, 3)
MIN_CURVE_SEGMENT_LEN = 0.05
MIN_CURVE_SEGMENT_ANGLE_DEG = 10
MAX_CURVE_SEGMENT_ANGLE_DEG = 170
